import { Router, type IRouter } from "express";

const router: IRouter = Router();

const PRODUCTS = [
  {
    id: "azul",
    name: "Colorante Azul",
    description: "Colorante artificial azul de alta concentración para uso alimentario.",
    price: 85,
    priceUnit: "100g",
    category: "Polvos",
    colors: ["#003F91"],
    imageUrl: null,
    inStock: true,
    featured: true,
    prices: { "25g": 35, "100g": 85, "500g": 250, "1kg": 450, "5kg": 1800 },
  },
  {
    id: "rosa",
    name: "Colorante Rosa",
    description: "Colorante artificial rosa/magenta de alta concentración para uso alimentario.",
    price: 85,
    priceUnit: "100g",
    category: "Polvos",
    colors: ["#FF2E63"],
    imageUrl: null,
    inStock: true,
    featured: true,
    prices: { "25g": 35, "100g": 85, "500g": 250, "1kg": 450, "5kg": 1800 },
  },
  {
    id: "verde",
    name: "Colorante Verde",
    description: "Colorante artificial verde brillante de alta concentración para uso alimentario.",
    price: 85,
    priceUnit: "100g",
    category: "Polvos",
    colors: ["#2ECC71"],
    imageUrl: null,
    inStock: true,
    featured: true,
    prices: { "25g": 35, "100g": 85, "500g": 250, "1kg": 450, "5kg": 1800 },
  },
  {
    id: "amarillo",
    name: "Colorante Amarillo",
    description: "Colorante artificial amarillo vibrante de alta concentración para uso alimentario.",
    price: 85,
    priceUnit: "100g",
    category: "Polvos",
    colors: ["#FFCD00"],
    imageUrl: null,
    inStock: true,
    featured: false,
    prices: { "25g": 35, "100g": 85, "500g": 250, "1kg": 450, "5kg": 1800 },
  },
  {
    id: "naranja",
    name: "Colorante Naranja",
    description: "Colorante artificial naranja brillante de alta concentración para uso alimentario.",
    price: 85,
    priceUnit: "100g",
    category: "Polvos",
    colors: ["#FF8C00"],
    imageUrl: null,
    inStock: true,
    featured: false,
    prices: { "25g": 35, "100g": 85, "500g": 250, "1kg": 450, "5kg": 1800 },
  },
  {
    id: "rojo",
    name: "Colorante Rojo",
    description: "Colorante artificial rojo intenso de alta concentración para uso alimentario.",
    price: 85,
    priceUnit: "100g",
    category: "Polvos",
    colors: ["#E53935"],
    imageUrl: null,
    inStock: true,
    featured: false,
    prices: { "25g": 35, "100g": 85, "500g": 250, "1kg": 450, "5kg": 1800 },
  },
  {
    id: "negro",
    name: "Colorante Negro",
    description: "Colorante artificial negro profundo de alta concentración para uso alimentario.",
    price: 85,
    priceUnit: "100g",
    category: "Polvos",
    colors: ["#1A1A2E"],
    imageUrl: null,
    inStock: true,
    featured: false,
    prices: { "25g": 35, "100g": 85, "500g": 250, "1kg": 450, "5kg": 1800 },
  },
  {
    id: "morado",
    name: "Colorante Morado",
    description: "Colorante artificial morado/violeta de alta concentración para uso alimentario.",
    price: 85,
    priceUnit: "100g",
    category: "Polvos",
    colors: ["#7B2FBE"],
    imageUrl: null,
    inStock: true,
    featured: false,
    prices: { "25g": 35, "100g": 85, "500g": 250, "1kg": 450, "5kg": 1800 },
  },
];

router.get("/products", (_req, res) => {
  res.json(PRODUCTS);
});

export default router;
